# Workaround for kcov. See https://github.com/travis-ci/travis-ci/issues/9061.
sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

addons:
  apt:
    packages:
    - bc
    - binutils-dev
    - libdw-dev
    - libelf-dev
    - time

script: ./travis.sh
