name: bench

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule: [{cron: '38 11 * * *'}]

jobs:
  lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path=lib/Cargo.toml
