name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule: [{cron: '38 11 * * *'}]

jobs:
  lib:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable, nightly]
        features:
          - ''
          - '--no-default-features --features=alloc'
          - '--no-default-features'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=lib/Cargo.toml --release ${{ matrix.features }}
  macro:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=lib/macro/Cargo.toml --release
