name: Coverage

on:
  push:
    branches: [main]

jobs:
  tarpaulin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup default nightly
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --coveralls=${{ secrets.COVERALLS_TOKEN }} --include-files=src/lib.rs
        working-directory: lib
